"""Recruiter outreach agent — Phase 3D facade."""
from __future__ import annotations

from jobforge.outreach.campaigns import (
    CreateCampaignRequest,
    DraftMessageRequest,
    OutreachMetrics,
    StatusUpdateRequest,
    campaign_to_dict,
    compute_metrics,
    create_campaign,
    draft_message,
    event_to_dict,
    get_campaign,
    list_campaigns,
    list_due_follow_ups,
    list_events,
    list_messages,
    list_recent_replies,
    mark_sent,
    message_row_to_dict,
    metrics_to_dict,
    update_status,
)
from jobforge.outreach.contacts import (
    OutreachError,
    UpsertContactRequest,
    contact_to_dict,
    delete_contact,
    discover_contacts,
    get_contact,
    list_contacts,
    upsert_contact,
)
from jobforge.outreach.messages import (
    ALL_KINDS,
    KIND_FOLLOW_UP,
    KIND_HM_INTRO,
    KIND_INITIAL,
    KIND_REFERRAL,
    KIND_THANK_YOU,
    DraftedMessage,
    MessageContext,
    MessageError,
    generate_message,
    message_to_dict,
)

__all__ = [
    "ALL_KINDS",
    "KIND_FOLLOW_UP",
    "KIND_HM_INTRO",
    "KIND_INITIAL",
    "KIND_REFERRAL",
    "KIND_THANK_YOU",
    "CreateCampaignRequest",
    "DraftMessageRequest",
    "DraftedMessage",
    "MessageContext",
    "MessageError",
    "OutreachError",
    "OutreachMetrics",
    "StatusUpdateRequest",
    "UpsertContactRequest",
    "campaign_to_dict",
    "compute_metrics",
    "contact_to_dict",
    "create_campaign",
    "delete_contact",
    "discover_contacts",
    "draft_message",
    "event_to_dict",
    "generate_message",
    "get_campaign",
    "get_contact",
    "list_campaigns",
    "list_contacts",
    "list_due_follow_ups",
    "list_events",
    "list_messages",
    "list_recent_replies",
    "mark_sent",
    "message_row_to_dict",
    "message_to_dict",
    "metrics_to_dict",
    "update_status",
    "upsert_contact",
]
